### ISSUE TITLE
Error out with incomplete filter files

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mg-scripts#14] opened 2020-06-05 00:42 UTC
In extreme cases if filter files are partially copied to our server, the resulting FASTQ files might have discordant number of sequences in the fwd and in the reverse reads. This is the error that bcl2fastq showed last time this happened:

```
>[7f0ca4b96700] ERROR: Thread: 5 caught an exception first: /home/redacted/bcl2fastq_2_20/bcl2fastq/src/cxx/lib/data/FileReader.cpp(102): Throw in function virtual void bcl2fastq::data::FileReader::logError(std::streamsize, std::streamsize) const
>Dynamic exception type: boost::exception_detail::clone_impl<bcl2fastq::common::InputDataError>
>std::exception::what: Filter file './Data/Intensities/BaseCalls/L004/s_4_1162.filter' truncated: bytes_read=605252 bytes_expected=4091904
```

**Comment by charles-cowart** [comment] 2023-09-14 22:27
This issue appears resolved with the migration to the SPP codebase.  The directories made available by @jdereus contain RTAComplete.txt files and the SPP as well as the earlier bash scripts check for the presence of this file before allowing a job to be created. My thinking is Jeff's process that generates this file is very reliable; I haven't seen this issue appear from bcl2fastq or bcl-convert in nearly two years of operation.

**Closed by charles-cowart** 2023-09-14 22:27 UTC
Labels: bug

**Comment by antgonza** [comment] 2024-10-17 19:14
Just hit this and with the help of @jdereus we figured out that the solution is to use bcl-convert 4.2.4 vs. 3.7.5; in the former the issue is a warning, while in the latter is an error.
